BooksCRM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings





urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('books_service.urls'), name="books"),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books_service/urls.py
from django.urls import path
from .views import AllBooks,ExistedBooks,SoldBook, SoldBooks,  Book, CreateBook, CreateAuthor, DeleteBookView, CreatePublisher, AuthorView, PublisherView, AllAuthorsView, AllPublishersView

urlpatterns = [
    path('all/', AllBooks.as_view(), name='all_books'),
    path('sold/', SoldBooks.as_view(), name='sold_books'),
    path('', ExistedBooks.as_view(), name='existed_books'),
    path('<int:pk>/', Book.as_view(), name='book_detail'),
    path('sold/<int:pk>/', SoldBook.as_view(), name='sold_book'),
    path('author/<int:pk>/', AuthorView.as_view(), name='author'),
    path('publisher/<int:pk>/', PublisherView.as_view(), name='publisher'),
    path('<int:pk>/edit', Book.as_view(), name='edit_book'),
    path('create', CreateBook.as_view(), name='create_book'),
    path('author/create', CreateAuthor.as_view(), name='create_author'),
    path('author/all', AllAuthorsView.as_view(), name='all_authors'),
    path('publisher/all', AllPublishersView.as_view(), name='all_publishers'),
    path('publisher/create', CreatePublisher.as_view(), name='create_publisher'),
    path('delete/<int:pk>', DeleteBookView.as_view(), name='delete_book'),

]

books_service/models.py
from django.db import models
from enum import Enum
# Create your models here.

class Author(models.Model):
    name = models.CharField(max_length=100)
    picture = models.ImageField(upload_to='static/', null=True, blank=True)



class Publisher(models.Model):
    name = models.CharField(max_length=100)

    def __repr__(self):
        return self.name
    def __str__(self):
        return self.name

class Books(models.Model):
    name = models.CharField(max_length=200, unique=False)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, null=True,blank=True)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE, null=True, blank=True)
    picture = models.ImageField(upload_to='media/', null=True, blank=True)
    price_in = models.IntegerField(null=False, blank=False)
    price_out = models.IntegerField(null=True, blank=True)
    grade = models.IntegerField(null=True, blank=True)
    bought = models.DateTimeField(null=True, blank=True)
    sold = models.DateTimeField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)

books_service/forms.py
from django.forms import ModelForm, HiddenInput, inlineformset_factory, modelformset_factory
from nested_formset import nestedformset_factory

from .models import Books, Author, Publisher

class AuthorForm(ModelForm):

    class Meta:
        model = Author
        fields = "__all__"


class PublisherForm(ModelForm):

    class Meta:
        model = Publisher
        fields = "__all__"



class BookForm(ModelForm):

    class Meta:
        model = Books
        fields = "__all__"

books_service/views.py
from datetime import datetime
from django.shortcuts import render
from django.urls import reverse_lazy

from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from .models import Books, Author, Publisher
from .forms import BookForm, AuthorForm, PublisherForm
from .utils import get_book_image, get_author_img
from django.core.files.base import ContentFile, File

# Create your views here.

class AllBooks(ListView):
    model = Books
    paginate_by = 5

    def get_ordering(self):
        ordering = self.request.GET.get('ordering', 'name')
        # validate ordering here
        return [ordering, ]

class ExistedBooks(ListView):
    model = Books
    template_name = 'books_service/existed_list_tamplate.html'
    def get_queryset(self,*args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        return qs.filter(price_out=None)

    def get_ordering(self):
        ordering = self.request.GET.get('ordering', 'name')
        # validate ordering here
        return [ordering, ]


class SoldBooks(ListView):
    model = Books
    template_name = 'books_service/sold_list_tamplate.html'
    def get_queryset(self,*args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        return qs.exclude(price_out=None)

    def get_ordering(self):
        ordering = self.request.GET.get('ordering', 'name')
        # validate ordering here
        return [ordering, ]


class Book(DetailView):
    model = Books

class AuthorView(DetailView):
    model = Author
    def get(self, *args, **kwargs):
        c=1
        return super().get(*args, **kwargs)

class CreateBook(CreateView):
    form_class = BookForm
    success_url = reverse_lazy("all_books")
    template_name = 'books_service/books_form.html'

    def get_context_data(self, **kwargs):
        context = super(CreateBook, self).get_context_data(**kwargs)
        context['authors'] = Author.objects.all()
        context['publishers'] = Publisher.objects.all()
        return context

    def form_valid(self, form):
        if not form.instance.picture:
            name, content = get_book_image(form.instance.name)
            if name:
                form.instance.picture.save(name, ContentFile(content))
        return super().form_valid(form)


    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if kwargs.get('data'):
            kwargs['data']._mutable = True
            kwargs['data']['bought'] = datetime.today().date()
            author, _saved = Author.objects.get_or_create(name=kwargs['data']['author'])
            if _saved:
                name, content = get_author_img(author.name)
                if name:
                    author.picture.save(name, ContentFile(content))
            kwargs['data']['author'] = author.id
            publisher, _saved = Publisher.objects.get_or_create(name=kwargs['data']['publisher'])
            kwargs['data']['publisher'] = publisher.id
            kwargs['data']._mutable = False
        return kwargs

class CreateAuthor(CreateView):
    form_class = AuthorForm
    success_url = reverse_lazy("all_books")
    template_name = 'books_service/author_form.html'


class CreatePublisher(CreateView):
    form_class = PublisherForm
    success_url = reverse_lazy("all_books")
    template_name = 'books_service/publisher_form.html'

class PublisherView(DetailView):
    model = Publisher

class AllPublishersView(ListView):
    model = Publisher

class AllAuthorsView(ListView):
    model = Author

class DeleteBookView(DeleteView):
    model = Books
    success_url = reverse_lazy("all_books")

class SoldBook(UpdateView):
    model = Books
    fields = ["price_out"]
    template_name = 'books_service/sold_form.html'
    success_url = reverse_lazy("existed_books")

books_service/templates/books_service/author_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% load i18n %}
    {% include 'books_service/header.html' %}

    <h1>{{ author.name }}</h1>
    {% if author.picture %}
        <td rowspan="2"><img height=120px src="{{ author.picture.url }}" ></td>
    {% else %}
        <td rowspan="2"><img height=120px src="/media/static/no_photo.jpeg" ></td>
    {% endif %}
    {% if author.books_set.all %}
        {% with books_list=author.books_set.all %}
            {%  include "books_service/books_list_tamplate.html" %}
        {%  endwith %}
    {% else %}
        <h2>{% trans "NoBooksYet" %}</h2>
    {% endif %}
</body>
</html>

books_service/templates/books_service/author_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% include 'books_service/header.html' %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
</body>
</html>

books_service/templates/books_service/author_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {%  load i18n %}
    {% include 'books_service/header.html' %}
    <table>
        <tr>
            <th>{% trans "AuthorLogo" %}</th>
            <th>{% trans "AuthorName" %}</th>
        </tr>
        {% for author in author_list %}
            <tr>
                <th><img height=120px src="{{ author.picture.url }}" ></th>
                <td><a href="{% url 'author' pk=author.id%}">{{ author.name }}</a></td>
            </tr>
        {% endfor %}
    </table>


</body>
</html>

books_service/templates/books_service/base_paginator.html
{% include 'books_service/header.html' %}
{% block list %}
{% endblock %}
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      </li>
    {% else %}
        <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="True">Previous</a>
      </li>
    {% endif %}

    {% if page_obj.number|add:'-4' > 1 %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'-5' }}">&hellip;</a></li>
    {% endif %}

    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
            <li class="page-item active" aria-current="page">
          <span class="page-link">
            {{ i }}
          </span>
        </li>
        {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
             <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
    {% endfor %}

    {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
       <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'5' }}">&hellip;</a></li>
    {% endif %}

    {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
      </li>
    {% else %}
        <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="True">Next</a>
      </li>
    {% endif %}
  </ul>
</nav>

books_service/templates/books_service/books_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% include 'books_service/header.html' %}
{% load i18n %}
<h1>{{ books.name }}</h1>
{% if books.picture %}
    <p><img height=120px src="{{ books.picture.url }}" ></p>
{% else %}
    <p><img height=120px src="/media/static/no_img.jpeg" ></p>
{% endif %}
<p><a href="{% url 'author' pk=books.author.id%}">{{ books.author.name }}</a> | <a href="{% url 'publisher' pk=books.publisher.id%}">{{ books.publisher.name }}</a></p>
<p>{% trans 'Grade' %} {{ books.grade }}</p>
<p>{% trans 'BoughtPrice' %} {{ books.price_in }}</p>
<p>{% trans 'SoldPrise' %} {{ books.price_out }}</p>
<p><label>{% trans "BookBought" %}  <input type="date" value="{{ books.bought.date|date:"Y-m-d"  }}" name="bought" readonly="true"></label></p>
{% if not books.sold %}
    <a>{% trans 'SoldBook' %}</a>
{% else %}
    <<p><label>{% trans "BookSoldDate" %}  <input type="date" value="{{ books.sold.date|date:"Y-m-d"  }}" name="sold" readonly="true"></label></p>

{%  endif %}
<p>{{ books.description }}</p>
</body>
</html>

books_service/templates/books_service/books_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% include 'books_service/header.html' %}
{% load i18n %}
 <form method="post" enctype="multipart/form-data">{% csrf_token %}
    <table>
        <tr>
            <td>{% trans "BookName" %}</td>
            <td>{{ form.name }}</td>
        </tr>

        <tr>
            <td>{% trans "Author" %}</td>
            <td><input type="text" name="author" id="id_author" list="autname">
                <datalist id="autname">
                    {% for author in authors %}
                      <option value={{ author.name }}>
                    {% endfor %}
                </datalist>
            </td>
        </tr>
        <tr>
            <td>{% trans "Publisher" %}</td>
            <td><input type="text" name="publisher" id="id_publisher" list="pubname">
                <datalist id="pubname">
                    {% for pub in publishers %}
                      <option value={{ pub.name }}>
                    {% endfor %}
                </datalist>
            </td>

        </tr>
        <tr>
            <td>{% trans "Picture" %}</td>
            <td>{{ form.picture }}</td>

        </tr>
        <tr>
            <td>{% trans "PriceIn" %}</td>
            <td>{{ form.price_in }}</td>
        </tr>
        <tr>
            <td>{% trans "Description" %}</td>
            <td>{{ form.description }}</td>
        </tr>

    </table>
    <input type="submit" value="Save" >
</form>
</body>
</html>

books_service/templates/books_service/books_list.html
{% extends 'books_service/base_paginator.html' %}
{%  block list %}
{%  load i18n %}

<div class="container-fluid">



<div class="table-striped">
  <table class="table">

    <tr>
        <th ><a  href="?ordering=name">{% trans "BookName" %}</a></th>
         <th ><a  href="?ordering=count">{% trans "Count" %}</a></th>
         <th >
             <a  href="?ordering=publisher">{% trans "BookPublisher" %}</a> |
             <a  href="?ordering=author">{% trans "BookAuthor" %}</a></th>
         <th ><a  href="?ordering=price_in">{% trans "BookPriceIn" %}</a></th>
         <th ><a  href="?ordering=bought">{% trans "Bought" %}</a></th>
         <th ><a  href="?ordering=sold">{% trans "Sold" %}</a></th>
         <th ><a  href="?ordering=price_out">{% trans "BookPriceOut" %}</a></th>
         <th >{% trans "SellBook" %}</th>

    </tr>
    {% for book in books_list %}
    <tr {% if book.price_out %} class="bg-danger" {% endif %}>
        <td ><a href="{% url 'book_detail' pk=book.id%}">{{ book.name }}</a></td>
        <td >{{ book.count }}</td>
        <td>
            <a href="{% url 'publisher' pk=book.publisher.id%}">{{ book.publisher.name }}</a> | <a href="{% url 'author' pk=book.author.id%}">{{ book.author.name }} </a>
        </td>
        <td>{{ book.price_in }} грн</td>
        <td>{{ book.bought.date.isoformat }}</td>
        <td>{{ book.sold.date.isoformat }}</td>
        <td>{{  book.price_out|default_if_none:"" }}</td>
        <td >
            {% if not  book.price_out %}
                <a href=" {% url 'sold_book' pk=book.id %}">{% trans "SellBook" %}</a></td>
            {% endif %}
    </tr>
    {% empty %}
        <h2>{% trans "NoBooks" %}</h2>
    {% endfor %}
      </table>
</div>
</div>
{% endblock %}

books_service/templates/books_service/books_list_tamplate.html
{%  load i18n %}
<table>
    <tr>
         <th>{% trans "BookName" %}</th>
         <th>{% trans "BookAuthor" %}/ {% trans "BookPublisher" %}</th>
         <th>{% trans "BookGrade" %}</th>
         <th>{% trans "BookPriceIn" %}</th>
         <th>{% trans "BookPriceOut" %}</th>
         <th>{% trans "BookBo" %}</th>

    </tr>
    {% for book in books_list %}

    <tr>
        <td ><a href="{% url 'book_detail' pk=book.id%}">{{ book.name }}</a></td>
        <td>
            <a href="{% url 'author' pk=book.author.id%}">{{ book.author.name }} </a> __
            <a href="{% url 'publisher' pk=book.publisher.id%}">{{ book.publisher.name }}</a>
        </td>
        <td >{%  if book.grade %}
                {% for n in ''|center:book.grade %}
                    <img height=12px src="/media/static/star.webp" >
                {% endfor %}</td>
            {% endif %}
        <td>{{ book.price_in }}</td>
        <td>{{ book.price_out }}</td>
        <td>{{ books.bought.date }}</td>
    </tr>
{% empty %}
    <h2>{% trans "NoBooks" %}</h2>
{% endfor %}

books_service/templates/books_service/existed_list_tamplate.html
{% extends 'books_service/base_paginator.html' %}

{%  load i18n %}
{%  block list %}
<div class="container-fluid">



<div class="table-striped">

<table class="table">
    <tr>
         <th>{% trans "BookName" %}</th>
         <th>{% trans "Count" %}</th>
         <th>{% trans "BookPublisher" %} | {% trans "BookAuthor" %}</th>
         <th>{% trans "BookPriceIn" %}</th>
         <th>{% trans "Bought" %}</th>
         <th>{% trans "SellBook" %}</th>

    </tr>
    {% for book in books_list %}
    <tr>
        <td ><a href="{% url 'book_detail' pk=book.id%}">{{ book.name }}</a></td>
        <td >{{ book.count }}</td>
        <td>
            <a href="{% url 'publisher' pk=book.publisher.id%}">{{ book.publisher.name }}</a> | <a href="{% url 'author' pk=book.author.id%}">{{ book.author.name }} </a>
        </td>
        <td>{{ book.price_in }} грн</td>
        <td>{{ book.bought.date.isoformat }}</td>
        <td><a href=" {% url 'sold_book' pk=book.id %}">{% trans "SellBook" %}</a></td>
    </tr>
{% empty %}
    <h2>{% trans "NoBooks" %}</h2>
{% endfor %}
</table>
</div>
</div>

{% endblock %}

books_service/templates/books_service/header.html
<head>
  <title>{% block title %}{% endblock %}</title>
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>
{% load i18n %}
{% load book_extras%}
<div class="container-fluid">
    <ul class="nav  nav-pills bg-info">
        <li class="nav-item">
            <a class="nav-link link-light" href="{% url 'existed_books' %}">{%  trans "ExistedBooks" %}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link link-light" href="{% url 'all_books' %}">{%  trans "AllBooks" %}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link link-light" href="{% url 'sold_books' %}">{%  trans "SoldBooks" %}</a>
        </li>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle link-light" data-bs-toggle="dropdown" href="#">{%  trans "AllAuthors" %}</a>
        <ul class="dropdown-menu">
          {% get_authors as authors %}
          {% for author in authors %}
             <li><a class="dropdown-item" href="{% url 'author' author.id%}">{{ author.name}}</a></li>
          {% endfor %}
        </ul>
        </li>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle link-light" data-bs-toggle="dropdown" href="#">{%  trans "AllPublishers" %}</a>
        <ul class="dropdown-menu">
          {% get_pub as publishers %}
          {% for pub in publishers %}
             <li><a class="dropdown-item" href="{% url 'publisher' pub.id%}">{{ pub.name}}</a></li>
          {% endfor %}
        </ul>
        </li>
        <li class="nav-item">
            <a class="nav-link link-light" href="{% url 'create_book' %}">+ {%  trans "AddNewBook" %}</a>
        </li>
    </ul>
</div>

books_service/templates/books_service/publisher_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% include 'books_service/header.html' %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
</body>
</html>

books_service/templates/books_service/sold_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% include 'books_service/header.html' %}
{% load i18n %}
<h1>{{ books.name }}</h1>
{% if book.picture %}
    <p><img height=120px src="{{ books.picture.url }}" ></p>
{% else %}
    <p><img height=120px src="/media/static/no_img.jpeg" ></p>
{% endif %}
<p><a href="{% url 'author' pk=books.author.id%}">{{ books.author.name }}</a></p>
<p>{{ book.grade }}</p>
<p>{{ book.price_in }}</p>

<p><a href="{% url 'publisher' pk=books.publisher.id%}">{{ books.publisher.name }}</a></p>
<p>{{ books.price_out }}</p>
<p><label>{% trans "BookBought" %}<input type="date" value="{{ books.bought }}" name="bought" min="2000-01-01" max=2040-01-01" readonly="true"></label></p>
{% if not book.sold %}
    <a>{% trans 'SoldBook' %}</a>
{% else %}
    <p>{{ books.sold }}</p>
{%  endif %}
<p>{{ books.description }}</p>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form></body>
</html>

books_service/templates/books_service/sold_list_tamplate.html
{% extends 'books_service/base_paginator.html' %}
{%  block list %}

{%  load i18n %}

<div class="container-fluid">

<div class="table-striped">
  <table class="table">
      <tr>
         <th ><a  href="?ordering=name">{% trans "BookName" %}</a></th>
         <th ><a  href="?ordering=author">{% trans "BookAuthor" %}</a></th>
         <th ><a  href="?ordering=publisher">{% trans "BookPublisher" %}</a></th>
         <th ><a  href="?ordering=grade">{% trans "BookGrade" %}</a></th>
         <th ><a  href="?ordering=price_in">{% trans "BookPriceIn" %}</a></th>
         <th ><a  href="?ordering=price_out">{% trans "BookPriceOut" %}</a></th>

    </tr>
    {% for book in books_list %}
    <tr>
        <td ><a href="{% url 'book_detail' pk=book.id%}">{{ book.name }}</a></td>
        <td><a href="{% url 'author' pk=book.author.id%}">{{ book.author.name }} </a></td>
        <td><a href="{% url 'publisher' pk=book.publisher.id%}">{{ book.publisher.name }}</a></td>
        <td >{%  if book.grade %}
                {% for n in ''|center:book.grade %}
                    <img height=12px src="/media/static/star.webp" >
                {% endfor %}</td>
            {% endif %}
        <td>{{ book.price_in }}</td>
        <td>{{ book.price_out }}</td>
    </tr>
{% empty %}
    <h2>{% trans "NoBooks" %}</h2>
{% endfor %}
  </table>
</div>
</div>
{% endblock %}